defaults:
  - config
  - model: flux2_dev
  - detector: flux2
  - dataset: artifacts
  - _self_

task:
  name: dataset_flux2

generation:
  height: ${model.height}
  width: ${model.width}
  num_steps: ${model.num_steps}
  guidance_scale: 4.0
  max_sequence_length: 256

output:
  run_name: ""
